.PHONY: all clean

all:
	@echo gcc receiver.c -o receiver
	@echo gcc sender.c -o sender
	@cp ../../Anisimov/lab9/semwrite.out sender
	@cp ../../Anisimov/lab9/semread.out receiver

clean:
	rm -f *.o receiver sender